version: "3.9"

services:

  database:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
  backend:
    image: ghcr.io/smileyfvce/film-react-nest/backend:review-2
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - frontend-network
      - backend-network

  frontend:
    image: ghcr.io/smileyfvce/film-react-nest/frontend:review-2
    env_file:
      - .env
    volumes:
      - frontend_dist:/dist

  nginx:
    image: ghcr.io/smileyfvce/film-react-nest/nginx:review-2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - frontend-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - backend-network

volumes:
  postgres_data:
  frontend_dist:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
